package com.service.booking.backend.enums;

public enum CityEnum {
    BEROVO,
    BITOLA,
    BOGDANCI,
    DELCHEVO,
    DEBAR,
    DEMIR_HISAR,
    DEMIR_KAPIJA,
    GEVGELIJA,
    GOSTIVAR,
    KAVADARCI,
    KICHEVO,
    KOCHANI,
    KRATOVO,
    KRIVA_PALANKA,
    KRUSHEVO,
    KUMANOVO,
    MAKEDONSKA_KAMENICA,
    MAKEDONSKI_BROD,
    NEGOTINO,
    OHRID,
    PEHCHEVO,
    PRILEP,
    PROBISHTIP,
    RADOVISH,
    RESEN,
    SHTIP,
    SKOPJE,
    STRUGA,
    STRUMICA,
    SVETI_NIKOLE,
    TETOVO,
    VALANDOVO,
    VELES,
    VINICA
}
