export const cities = [
  { value: 'SKOPJE', label: 'Скопје' },
  { value: 'BITOLA', label: 'Битола' },
  { value: 'OHRID', label: 'Охрид' },
  { value: 'KUMANOVO', label: 'Куманово' },
  { value: 'TETOVO', label: 'Тетово' },
  { value: 'STRUMICA', label: 'Струмица' },
  { value: 'VELES', label: 'Велес' },
  { value: 'PRILEP', label: 'Прилеп' },
  { value: 'KICHEVO', label: 'Кичево' },
  { value: 'KRIVA_PALANKA', label: 'Крива Паланка' },
  { value: 'BEROVO', label: 'Берово' },
  { value: 'BOGDANCI', label: 'Богданци' },
  { value: 'DEBAR', label: 'Дебар' },
  { value: 'DELCHEVO', label: 'Делчево' },
  { value: 'DEMIR_HISAR', label: 'Демир Хисар' },
  { value: 'DEMIR_KAPIJA', label: 'Демир Капија' },
  { value: 'GEVGELIJA', label: 'Гевгелија' },
  { value: 'GOSTIVAR', label: 'Гостивар' },
  { value: 'KAVADARCI', label: 'Кавадарци' },
  { value: 'KOCHANI', label: 'Кочани' },
  { value: 'KRATOVO', label: 'Кратово' },
  { value: 'KRUSHEVO', label: 'Крушево' },
  { value: 'MAKEDONSKA_KAMENICA', label: 'Македонска Каменица' },
  { value: 'MAKEDONSKI_BROD', label: 'Македонски Брод' },
  { value: 'NEGOTINO', label: 'Неготино' },
  { value: 'PEHCHEVO', label: 'Пехчево' },
  { value: 'PROBISHTIP', label: 'Пробиштип' },
  { value: 'RADOVISH', label: 'Радовиш' },
  { value: 'RESEN', label: 'Ресен' },
  { value: 'SHTIP', label: 'Штип' },
  { value: 'STRUGA', label: 'Струга' },
  { value: 'SVETI_NIKOLE', label: 'Свети Николе' },
  { value: 'VALANDOVO', label: 'Валандово' },
  { value: 'VINICA', label: 'Виница' },
];
